#!/usr/bin/env python3
"""Extract Apollo/Athene Q2 2026 retirement and spread metrics from the supplement."""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

import openpyxl


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "raw/primary-sources/capital-flow/apollo/q2-2026/apollo-q2-2026-financial-supplement.xlsx"
OUTPUT = ROOT / "analysis/company-first-principles/data/capital-flow-apollo-athene-q2-2026-extractions.csv"


@dataclass(frozen=True)
class MetricSpec:
    claim_id: str
    metric: str
    sheet: str
    row_label: str
    unit: str
    interpretation: str
    claim_effect: str


SPECS = [
    MetricSpec(
        "CF-004",
        "retirement services total gross inflows",
        "RS Flows and IA",
        "Total gross inflows",
        "USD millions",
        "Measures new retirement-services liability inflow feeding the Apollo/Athene engine.",
        "supports liability-source side of insurance/private-credit mechanism",
    ),
    MetricSpec(
        "CF-004",
        "retirement services net flows",
        "RS Flows and IA",
        "Net flows",
        "USD millions",
        "Measures net retained retirement-services flow after outflows.",
        "supports persistence of liability funding rather than only gross sales",
    ),
    MetricSpec(
        "CF-004",
        "inflows attributable to Athene",
        "RS Flows and IA",
        "Inflows attributable to Athene",
        "USD millions",
        "Separates Athene-attributable flows from ADIP and third-party reinsurance channels.",
        "supports Athene-specific liability funding channel",
    ),
    MetricSpec(
        "CF-004",
        "gross invested assets",
        "RS Flows and IA",
        "Gross invested assets",
        "USD millions",
        "Measures the asset base backing retirement-services liabilities.",
        "supports scale of investable asset pool",
    ),
    MetricSpec(
        "CF-004",
        "net invested assets",
        "RS Flows and IA",
        "Net invested assets13",
        "USD millions",
        "Measures investments directly backing Athene net reserve liabilities and surplus assets.",
        "supports durable liability-backed asset base",
    ),
    MetricSpec(
        "CF-004",
        "gross alternative investments",
        "Reconciliation_NIA and Alts",
        "Gross alternative investments",
        "USD millions",
        "Measures alternative-investment exposure inside the retirement-services investment base.",
        "supports private-assets allocation inside insurance-linked capital",
    ),
    MetricSpec(
        "CF-004",
        "net alternative investments",
        "Reconciliation_NIA and Alts",
        "Net alternative investments",
        "USD millions",
        "Measures net alternative-investment exposure after ACRA non-controlling interests.",
        "supports private-assets allocation after ownership adjustments",
    ),
    MetricSpec(
        "CF-004",
        "spread related earnings",
        "Summary",
        "Spread Related Earnings",
        "USD millions",
        "Measures earnings generated by Apollo's retirement-spread economics.",
        "supports economic conversion from liabilities and invested assets into earnings",
    ),
    MetricSpec(
        "CF-001",
        "fee related earnings",
        "Summary",
        "Fee Related Earnings",
        "USD millions",
        "Measures recurring fee economics of the asset-management platform.",
        "supports platform monetization alongside spread economics",
    ),
    MetricSpec(
        "CF-001",
        "credit management fees",
        "Total Segment Earnings",
        "Credit",
        "USD millions",
        "Measures management-fee contribution from Apollo's credit platform.",
        "supports credit platform fee scale",
    ),
]


def normalize(value: object) -> str:
    return str(value).strip() if value is not None else ""


def pct_change(current: float | int | None, prior: float | int | None) -> str:
    if current is None or prior in (None, 0):
        return ""
    return f"{((current - prior) / abs(prior)) * 100:.1f}"


def find_period_columns(ws) -> dict[str, int]:
    for row in ws.iter_rows(min_row=1, max_row=5):
        labels = {normalize(cell.value): cell.column for cell in row if normalize(cell.value)}
        if "2Q'26" in labels:
            return labels
    raise ValueError(f"Could not find period header in sheet {ws.title}")


def find_row(ws, label: str) -> int:
    for row in ws.iter_rows():
        first = normalize(row[0].value)
        if first == label:
            return row[0].row
    raise ValueError(f"Could not find row label {label!r} in sheet {ws.title}")


def main() -> int:
    wb = openpyxl.load_workbook(SOURCE, data_only=True, read_only=True)
    rows: list[dict[str, str]] = []

    for spec in SPECS:
        ws = wb[spec.sheet]
        columns = find_period_columns(ws)
        row_idx = find_row(ws, spec.row_label)
        current_column = columns["2Q'26"]
        q2_2026 = ws.cell(row_idx, columns["2Q'26"]).value
        q1_2026 = ws.cell(row_idx, columns["1Q'26"]).value
        q2_2025 = ws.cell(row_idx, columns["2Q'25"]).value
        rows.append(
            {
                "claim_id": spec.claim_id,
                "company": "Apollo / Athene",
                "period": "Q2 2026",
                "metric": spec.metric,
                "value": str(q2_2026),
                "unit": spec.unit,
                "qoq_reference_value": str(q1_2026),
                "qoq_change_pct": pct_change(q2_2026, q1_2026),
                "yoy_reference_value": str(q2_2025),
                "yoy_change_pct": pct_change(q2_2026, q2_2025),
                "source_file": str(SOURCE.relative_to(ROOT)),
                "source_location": f"{spec.sheet}!{ws.cell(row_idx, current_column).coordinate}",
                "interpretation": spec.interpretation,
                "claim_effect": spec.claim_effect,
                "status": "extracted-from-primary-supplement",
            }
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    print(f"wrote {len(rows)} Apollo/Athene extraction rows to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
