#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

required_files=(
  "notes/insight-extraction-hub-2026-08-11.md"
  "notes/master-insight-extraction-goal-2026-08-11.md"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md"
  "notes/insight-extraction-templates-2026-08-11.md"
  "notes/insight-artifact-manifest-2026-08-11.md"
  "notes/insight-driven-next-lane-queue-2026-08-11.md"
  "analysis/cross-sector/company-level-strategy-insight-guide-2026-08-10.md"
  "analysis/cross-sector/industry-level-strategy-guide-2026-08-10.md"
  "analysis/cross-sector/concrete-insights-and-curiosity-map-2026-08-10.md"
  "analysis/cross-sector/metric-glossary-and-watchlist-2026-08-10.md"
  "analysis/cross-sector/thesis-breaker-index-2026-08-10.md"
  "analysis/cross-sector/aha-moments-and-curiosity-questions-2026-08-10.md"
  "analysis/cross-sector/ai-physical-capacity-proof-2026-08-10.md"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md"
  "analysis/cross-sector/hidden-operating-infrastructure-proof-2026-08-10.md"
  "analysis/cross-sector/selective-consumer-proof-2026-08-10.md"
  "analysis/cross-sector/fandom-identity-participation-proof-2026-08-10.md"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md"
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md"
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md"
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md"
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md"
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-outside-hospital-proof-2026-08-10.md"
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-burden-vs-workflow-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md"
  "analysis/cross-sector/trust-as-paid-product-proof-2026-08-10.md"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md"
  "analysis/cross-sector/relationship-owner-vs-burden-carrier-proof-2026-08-10.md"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md"
  "analysis/cross-sector/commodity-chain-proof-2026-08-10.md"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md"
  "analysis/cross-sector/taxonomy-blind-spots-proof-2026-08-10.md"
  "site/index.html"
  "site/concrete-insights.html"
)

required_patterns=(
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Company"
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Lane"
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Theme"
  "notes/master-insight-extraction-goal-2026-08-11.md:No broad claim without concrete filing evidence"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:Master Instruction Block"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:The Required Evidence Chain"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:What A Finished Insight Should Sound Like"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md:Reusable Master Instruction"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md:The standard evidence chain is"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:Step 1: Define The Lane"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:Step 8: Write The Proof Memo"
  "notes/insight-extraction-templates-2026-08-11.md:Company Packet Template"
  "notes/insight-extraction-templates-2026-08-11.md:Run Closeout Template"
  "notes/insight-artifact-manifest-2026-08-11.md:Required Insight System Layers"
  "notes/insight-artifact-manifest-2026-08-11.md:Proof Memo Inventory"
  "notes/insight-driven-next-lane-queue-2026-08-11.md:Best Immediate Next Move"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Clean Capture Versus Burden Carrier Map"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Backlog Conversion Analysis"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Power And Skilled-Labor Bottleneck"
  "analysis/cross-sector/healthcare-burden-vs-workflow-comparison-2026-08-11.md:Burden Versus Cleaner Workflow Map"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Recurring Care Workflow Map"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Diagnostic Information Versus Therapy Delivery Distinction"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Distribution Versus Installed Workflow Distinction"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Occasion Versus Routine Demand Map"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Brand Relationship Versus Inventory And Support Burden"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Queue Status"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:Paid Relationship Map"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:“Subscription” is too blunt a category."
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:The best paid relationships reduce friction before the next decision."
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Status And Wallet Map"
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Status systems get stronger when they capture spend beyond the core activity."
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Co-brand and partner structures can be as important as direct customer behavior."
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:Continuity Versus Upgrade Map"
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:Maintenance is not a narrow industrial idea."
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:The stronger conclusion is that a large part of the modern economy is built around continuity spending."
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:Overhead And Control-Plane Map"
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:Complexity itself is becoming a monetizable demand driver."
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:When the cost of disorder rises, the company that reduces disorder can become a durable toll collector."
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:Coordination Toll Map"
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:Fragmented systems create attractive coordination tolls."
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:When a market is fragmented and the customer needs help navigating it repeatedly, the coordination layer can become more valuable than a large share of the underlying asset base."
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed Loop Versus Open Routing Map"
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed loops and open routers both sit in the middle, but they monetize different customer behavior."
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed loops maximize retained behavior, while open routers maximize useful choice."
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:Access System Map"
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:Access can be more important than ownership when repeat behavior matters."
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:When repeat use matters more than one-time ownership, the company that controls access can build a stronger relationship than the company selling isolated transactions."
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Aging Burden Map"
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Home is becoming the default setting for more of the aging system."
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Aging produces more logistics than most demographic language suggests."
  "analysis/cross-sector/healthcare-outside-hospital-proof-2026-08-10.md:healthcare-burden-vs-workflow-comparison-2026-08-11.md"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Standards Versus Vendors Distinction"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Proof Layer Economics"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Queue Status"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Property Burden Map"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Senior housing breaks the simple asset-light rule."
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Data centers show when property becomes infrastructure instead of generic real estate."
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Chain-By-Chain Comparison"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Input Cost Versus End-Market Demand Map"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Tariff And Policy Watchlist"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:Attention Owner Versus Attention Helper Comparison"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:Trust Versus Reach Distinction"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:AI Impact Curiosity Section"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Role Map"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Owning attention is not the same as owning the money flow."
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Commerce intent is becoming part of the media stack."
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Interface Ownership Map"
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Asset-light does not mean low burden. It means the burden moves."
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Local commerce is becoming more like operating infrastructure."
  "site/concrete-insights.html:AI capacity burden carrier comparison"
  "site/concrete-insights.html:Recreation lifestyle and occasion demand comparison"
  "site/concrete-insights.html:Paid relationship and habit loop comparison"
  "site/concrete-insights.html:Status wallet and default spend comparison"
  "site/concrete-insights.html:Continuity and maintenance economics comparison"
  "site/concrete-insights.html:Institutional overhead and control-plane comparison"
  "site/concrete-insights.html:Coordination toll without asset ownership comparison"
  "site/concrete-insights.html:Closed-loop ecosystem versus open routing comparison"
  "site/concrete-insights.html:Access instead of ownership comparison"
  "site/concrete-insights.html:Aging as operating reality comparison"
  "site/concrete-insights.html:Healthcare burden versus workflow comparison"
  "site/concrete-insights.html:Healthcare testing distribution and delivery comparison"
  "site/concrete-insights.html:Trust proof measurement and security comparison"
  "site/concrete-insights.html:Commodity chain comparison"
  "site/concrete-insights.html:Media attention helper comparison"
  "site/concrete-insights.html:Media owner versus helper economics comparison"
  "site/concrete-insights.html:Interface ownership and demand orchestration comparison"
  "site/concrete-insights.html:Relationship ownership versus property burden comparison"
  "site/index.html:Insight extraction hub"
  "site/index.html:Meaty end-to-end insight goal"
  "site/index.html:Lane end-to-end execution runbook"
  "site/index.html:Insight-driven next lane queue"
  "site/concrete-insights.html:Insight extraction hub"
  "site/concrete-insights.html:Meaty end-to-end insight goal"
  "site/concrete-insights.html:Lane end-to-end execution runbook"
  "site/concrete-insights.html:Insight-driven next lane queue"
)

for path in "${required_files[@]}"; do
  if [[ ! -s "$path" ]]; then
    printf 'missing or empty required file: %s\n' "$path" >&2
    exit 1
  fi
done

for item in "${required_patterns[@]}"; do
  path="${item%%:*}"
  pattern="${item#*:}"
  if ! rg -q --fixed-strings "$pattern" "$path"; then
    printf 'missing required pattern in %s: %s\n' "$path" "$pattern" >&2
    exit 1
  fi
done

printf 'insight-system-ok\n'
