#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

required_files=(
  "notes/insight-extraction-hub-2026-08-11.md"
  "notes/master-insight-extraction-goal-2026-08-11.md"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md"
  "notes/insight-extraction-templates-2026-08-11.md"
  "notes/insight-completion-rubric-2026-08-11.md"
  "notes/insight-artifact-manifest-2026-08-11.md"
  "notes/insight-driven-next-lane-queue-2026-08-11.md"
  "analysis/cross-sector/company-level-strategy-insight-guide-2026-08-10.md"
  "analysis/cross-sector/industry-level-strategy-guide-2026-08-10.md"
  "analysis/cross-sector/concrete-insights-and-curiosity-map-2026-08-10.md"
  "analysis/cross-sector/metric-glossary-and-watchlist-2026-08-10.md"
  "analysis/cross-sector/thesis-breaker-index-2026-08-10.md"
  "analysis/cross-sector/aha-moments-and-curiosity-questions-2026-08-10.md"
  "analysis/cross-sector/ai-physical-capacity-proof-2026-08-10.md"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md"
  "analysis/cross-sector/hidden-operating-infrastructure-proof-2026-08-10.md"
  "analysis/cross-sector/selective-consumer-proof-2026-08-10.md"
  "analysis/cross-sector/fandom-identity-participation-proof-2026-08-10.md"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md"
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md"
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md"
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md"
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md"
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md"
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md"
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md"
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md"
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md"
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md"
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md"
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md"
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-outside-hospital-proof-2026-08-10.md"
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md"
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-burden-vs-workflow-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md"
  "analysis/cross-sector/trust-as-paid-product-proof-2026-08-10.md"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md"
  "analysis/cross-sector/relationship-owner-vs-burden-carrier-proof-2026-08-10.md"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md"
  "analysis/cross-sector/commodity-chain-proof-2026-08-10.md"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md"
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md"
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md"
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md"
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md"
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md"
  "analysis/cross-sector/labor-production-infrastructure-comparison-2026-08-11.md"
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md"
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md"
  "analysis/cross-sector/packaging-as-demand-sensor-and-product-interface-comparison-2026-08-11.md"
  "analysis/cross-sector/low-friction-entrepreneurship-infrastructure-comparison-2026-08-11.md"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md"
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md"
  "analysis/cross-sector/externally-supplied-inventory-and-participation-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/taxonomy-blind-spots-proof-2026-08-10.md"
  "site/index.html"
  "site/concrete-insights.html"
)

required_patterns=(
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Company"
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Lane"
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Theme"
  "notes/master-insight-extraction-goal-2026-08-11.md:No broad claim without concrete filing evidence"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:Master Instruction Block"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:The Required Evidence Chain"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:What A Finished Insight Should Sound Like"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md:Reusable Master Instruction"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md:The standard evidence chain is"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:Step 1: Define The Lane"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:Step 8: Write The Proof Memo"
  "notes/insight-extraction-templates-2026-08-11.md:Company Packet Template"
  "notes/insight-extraction-templates-2026-08-11.md:Run Closeout Template"
  "notes/insight-completion-rubric-2026-08-11.md:Company Packet Rubric"
  "notes/insight-completion-rubric-2026-08-11.md:Lane Summary Rubric"
  "notes/insight-completion-rubric-2026-08-11.md:Proof Memo Rubric"
  "notes/insight-completion-rubric-2026-08-11.md:Fast Failure Tests"
  "notes/insight-artifact-manifest-2026-08-11.md:Required Insight System Layers"
  "notes/insight-artifact-manifest-2026-08-11.md:Proof Memo Inventory"
  "notes/insight-driven-next-lane-queue-2026-08-11.md:Best Immediate Next Move"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Clean Capture Versus Burden Carrier Map"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Backlog Conversion Analysis"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Power And Skilled-Labor Bottleneck"
  "analysis/cross-sector/healthcare-burden-vs-workflow-comparison-2026-08-11.md:Burden Versus Cleaner Workflow Map"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Recurring Care Workflow Map"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Diagnostic Information Versus Therapy Delivery Distinction"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Distribution Versus Installed Workflow Distinction"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Occasion Versus Routine Demand Map"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Brand Relationship Versus Inventory And Support Burden"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Queue Status"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:Paid Relationship Map"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:“Subscription” is too blunt a category."
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:The best paid relationships reduce friction before the next decision."
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Status And Wallet Map"
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Status systems get stronger when they capture spend beyond the core activity."
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Co-brand and partner structures can be as important as direct customer behavior."
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:Continuity Versus Upgrade Map"
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:Maintenance is not a narrow industrial idea."
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:The stronger conclusion is that a large part of the modern economy is built around continuity spending."
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:Overhead And Control-Plane Map"
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:Complexity itself is becoming a monetizable demand driver."
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:When the cost of disorder rises, the company that reduces disorder can become a durable toll collector."
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:Coordination Toll Map"
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:Fragmented systems create attractive coordination tolls."
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:When a market is fragmented and the customer needs help navigating it repeatedly, the coordination layer can become more valuable than a large share of the underlying asset base."
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed Loop Versus Open Routing Map"
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed loops and open routers both sit in the middle, but they monetize different customer behavior."
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed loops maximize retained behavior, while open routers maximize useful choice."
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:Access System Map"
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:Access can be more important than ownership when repeat behavior matters."
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:When repeat use matters more than one-time ownership, the company that controls access can build a stronger relationship than the company selling isolated transactions."
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md:Self-Maintenance Map"
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md:Confidence is an economic variable."
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md:When a business helps the customer stay ready, comfortable, or confident in repeatable ways, the spending can remain resilient even when consumers become more selective elsewhere."
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md:Discovery And Decision-Reduction Map"
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md:Abundance creates a new layer of economic value."
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md:When supply gets too broad for the customer to sort efficiently alone, the interface that reduces choice overload can become one of the strongest profit pools in the system."
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md:Relationship-Thickening Map"
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md:The first customer relationship is often only the start of the business."
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md:Once a company owns a durable customer relationship, the next big economic unlock often comes from adding a second layer on top of it rather than only growing the original product."
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md:Standardization Map"
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md:Simplification is a real product, not a byproduct."
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md:When complexity becomes painful enough, the company that makes the workflow more uniform can become one of the most durable toll collectors in the system."
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md:Delegation Map"
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md:These companies are often selling relief, not just output."
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md:They are selling fewer broken handoffs."
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md:Failure-Avoidance Map"
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md:Prevention spending is often easier to justify than repair spending."
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md:They are core economic layers."
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md:Compliance Map"
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md:Compliance demand is often more recurring than preference-based demand."
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md:It is also a demand engine."
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md:Labor-Scarcity Map"
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md:Backlog and demand are only meaningful if qualified labor exists to convert them."
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md:That is why specialist labor should be treated as a core economic layer, not just as an operating headache."
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md:Density Map"
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md:Density often looks boring until it compounds."
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md:the dense network can become the real product."
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md:Adaptation Map"
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md:Institutions increasingly buy adaptation capacity, not just outside opinions."
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md:It is outsourced adaptation."
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Aging Burden Map"
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Home is becoming the default setting for more of the aging system."
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Aging produces more logistics than most demographic language suggests."
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md:Beauty-Interface Map"
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md:The beauty winner is often the company that shortens the trend-to-purchase cycle."
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md:The stronger conclusion is that beauty is one of the archive's clearest examples of a consumer category turning into a discovery-and-data interface."
  "analysis/cross-sector/healthcare-outside-hospital-proof-2026-08-10.md:healthcare-burden-vs-workflow-comparison-2026-08-11.md"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Standards Versus Vendors Distinction"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Proof Layer Economics"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Queue Status"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Property Burden Map"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Senior housing breaks the simple asset-light rule."
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Data centers show when property becomes infrastructure instead of generic real estate."
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Chain-By-Chain Comparison"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Input Cost Versus End-Market Demand Map"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Tariff And Policy Watchlist"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:Attention Owner Versus Attention Helper Comparison"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:Trust Versus Reach Distinction"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:AI Impact Curiosity Section"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Role Map"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Owning attention is not the same as owning the money flow."
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Commerce intent is becoming part of the media stack."
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Interface Ownership Map"
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Asset-light does not mean low burden. It means the burden moves."
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Local commerce is becoming more like operating infrastructure."
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md:Point-Of-Use Control Map"
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md:The most defensible part of the system is often the part that the user actually touches."
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md:The stronger conclusion is that some of the best businesses in the archive win by owning the qualified point of use."
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md:Narrow Chokepoint Map"
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md:A small layer can control a much larger economic system."
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's best recurring patterns is not scale alone."
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md:Reapproval Friction Map"
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md:Switching cost is often too vague a phrase."
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's best businesses are protected by the cost of reopening a trusted system."
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md:Pull-Through Map"
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md:The initial sale often understates the real business."
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's best businesses are not one-time product businesses at all."
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md:Accepted-Record Map"
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md:The valuable layer is often the accepted record, not only the workflow tool."
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's best recurring businesses own the accepted record inside a workflow."
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md:Frontline-Visibility Map"
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md:A lot of value sits in making work legible at the frontline."
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's underappreciated economic layers is frontline visibility."
  "analysis/cross-sector/labor-production-infrastructure-comparison-2026-08-11.md:Labor-Production Map"
  "analysis/cross-sector/labor-production-infrastructure-comparison-2026-08-11.md:Labor shortages create demand one step upstream from hiring."
  "analysis/cross-sector/labor-production-infrastructure-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's underappreciated growth systems is labor production itself."
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md:Machine-Readable-State Map"
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md:Many high-value systems begin by making reality legible."
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's quieter but important economic layers is standardized operating state."
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md:Decision-Authority Map"
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md:Institutions often pay to narrow the choice set before they act."
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's most important financial layers is outsourced decision authority."
  "analysis/cross-sector/packaging-as-demand-sensor-and-product-interface-comparison-2026-08-11.md:Packaging-Economics Map"
  "analysis/cross-sector/packaging-as-demand-sensor-and-product-interface-comparison-2026-08-11.md:Packaging is often a better read on real demand than the shelf story alone."
  "analysis/cross-sector/packaging-as-demand-sensor-and-product-interface-comparison-2026-08-11.md:The stronger conclusion is that packaging is one of the archive's better hidden readouts on both demand quality and physical burden."
  "analysis/cross-sector/low-friction-entrepreneurship-infrastructure-comparison-2026-08-11.md:Entrepreneurship-Infrastructure Map"
  "analysis/cross-sector/low-friction-entrepreneurship-infrastructure-comparison-2026-08-11.md:The stronger conclusion is that a large part of modern entrepreneurship now depends on access to infrastructure"
  "analysis/cross-sector/low-friction-entrepreneurship-infrastructure-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md:Commitment-Friction Map"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md:The stronger conclusion is that a growing part of the economy is being optimized around commitment friction"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md:Intent-Capture Map"
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md:The stronger conclusion is that one of the next important economic layers in commerce is not just who owns the destination site."
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/externally-supplied-inventory-and-participation-economics-comparison-2026-08-11.md:External-Supply Map"
  "analysis/cross-sector/externally-supplied-inventory-and-participation-economics-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's recurring economic patterns is the rise of businesses whose real inventory is supplied from the outside."
  "analysis/cross-sector/externally-supplied-inventory-and-participation-economics-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "site/concrete-insights.html:AI capacity burden carrier comparison"
  "site/concrete-insights.html:Insight completion rubric"
  "site/concrete-insights.html:Recreation lifestyle and occasion demand comparison"
  "site/concrete-insights.html:Paid relationship and habit loop comparison"
  "site/concrete-insights.html:Status wallet and default spend comparison"
  "site/concrete-insights.html:Continuity and maintenance economics comparison"
  "site/concrete-insights.html:Institutional overhead and control-plane comparison"
  "site/concrete-insights.html:Coordination toll without asset ownership comparison"
  "site/concrete-insights.html:Closed-loop ecosystem versus open routing comparison"
  "site/concrete-insights.html:Access instead of ownership comparison"
  "site/concrete-insights.html:Self-maintenance and confidence spend comparison"
  "site/concrete-insights.html:Discovery and decision reduction comparison"
  "site/concrete-insights.html:Relationship thickening and second-layer monetization comparison"
  "site/concrete-insights.html:Standardization and simplification as product comparison"
  "site/concrete-insights.html:Delegated operations and outsourced complexity comparison"
  "site/concrete-insights.html:Failure avoidance and uptime economics comparison"
  "site/concrete-insights.html:Compliance and mandated spend economics comparison"
  "site/concrete-insights.html:Specialist labor and certified capacity comparison"
  "site/concrete-insights.html:Density and local coverage as moat comparison"
  "site/concrete-insights.html:Institutional adaptation and capability outsourcing comparison"
  "site/concrete-insights.html:Aging as operating reality comparison"
  "site/concrete-insights.html:Beauty discovery and data interface comparison"
  "site/concrete-insights.html:Healthcare burden versus workflow comparison"
  "site/concrete-insights.html:Healthcare testing distribution and delivery comparison"
  "site/concrete-insights.html:Trust proof measurement and security comparison"
  "site/concrete-insights.html:Commodity chain comparison"
  "site/concrete-insights.html:Media attention helper comparison"
  "site/concrete-insights.html:Media owner versus helper economics comparison"
  "site/concrete-insights.html:Interface ownership and demand orchestration comparison"
  "site/concrete-insights.html:Point-of-use control and qualified interface comparison"
  "site/concrete-insights.html:Narrow chokepoint and disproportionate consequence comparison"
  "site/concrete-insights.html:Qualification, validation, and reapproval friction comparison"
  "site/concrete-insights.html:Installed-base and pull-through economics comparison"
  "site/concrete-insights.html:Accepted record and auditable workflow control comparison"
  "site/concrete-insights.html:Frontline visibility and executable workflow comparison"
  "site/concrete-insights.html:Labor production infrastructure comparison"
  "site/concrete-insights.html:Machine-readable operating state comparison"
  "site/concrete-insights.html:Outsourced judgment and benchmark authority comparison"
  "site/concrete-insights.html:Packaging as demand sensor and product interface comparison"
  "site/concrete-insights.html:Low-friction entrepreneurship infrastructure comparison"
  "site/concrete-insights.html:Deferred commitment and conversion infrastructure comparison"
  "site/concrete-insights.html:Intent capture and agentic commerce interface comparison"
  "site/concrete-insights.html:Externally supplied inventory and participation economics comparison"
  "site/concrete-insights.html:Relationship ownership versus property burden comparison"
  "site/index.html:Insight extraction hub"
  "site/index.html:Meaty end-to-end insight goal"
  "site/index.html:Lane end-to-end execution runbook"
  "site/index.html:Insight-driven next lane queue"
  "site/concrete-insights.html:Insight extraction hub"
  "site/concrete-insights.html:Meaty end-to-end insight goal"
  "site/concrete-insights.html:Lane end-to-end execution runbook"
  "site/concrete-insights.html:Insight-driven next lane queue"
)

for path in "${required_files[@]}"; do
  if [[ ! -s "$path" ]]; then
    printf 'missing or empty required file: %s\n' "$path" >&2
    exit 1
  fi
done

for item in "${required_patterns[@]}"; do
  path="${item%%:*}"
  pattern="${item#*:}"
  if ! rg -q --fixed-strings "$pattern" "$path"; then
    printf 'missing required pattern in %s: %s\n' "$path" "$pattern" >&2
    exit 1
  fi
done

printf 'insight-system-ok\n'
