#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

reusable_note_manifest="indexes/reusable-note-layer-files-2026-08-11.txt"
historical_note_manifest="indexes/historical-note-exclusion-files-2026-08-11.txt"
note_boundary_report="notes/note-layer-boundary-audit-2026-08-11.md"
note_boundary_json="notes/note-layer-boundary-audit-2026-08-11.json"

required_files=(
  "README.md"
  "START-HERE.md"
  "$reusable_note_manifest"
  "$historical_note_manifest"
  "indexes/historical-note-exclusion-categories-2026-08-11.tsv"
  "indexes/legacy-root-raw-reference-top-files-2026-08-11.tsv"
  "scripts/audit-note-layer-boundary.sh"
  "scripts/audit-browser-review-links.sh"
  "scripts/audit-legacy-root-references.sh"
  "scripts/refresh-note-layer-boundary.sh"
  "scripts/resolve-offloaded-raw-path.py"
  "scripts/verify-raw-evidence-governance.sh"
  "$note_boundary_report"
  "$note_boundary_json"
  "notes/insight-extraction-hub-2026-08-11.md"
  "notes/master-insight-extraction-goal-2026-08-11.md"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md"
  "notes/end-to-end-insight-operator-and-review-brief-2026-08-11.md"
  "notes/remaining-end-to-end-insight-goal-2026-08-11.md"
  "notes/remaining-insight-execution-board-2026-08-11.md"
  "notes/master-operator-brief-2026-08-10.md"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md"
  "notes/insight-extraction-templates-2026-08-11.md"
  "notes/insight-completion-rubric-2026-08-11.md"
  "notes/insight-artifact-manifest-2026-08-11.md"
  "notes/raw-evidence-link-policy-2026-08-11.md"
  "notes/legacy-root-reference-audit-2026-08-11.md"
  "notes/legacy-root-reference-audit-2026-08-11.json"
  "notes/insight-note-standardization-cutoff-2026-08-11.md"
  "notes/insight-driven-next-lane-queue-2026-08-11.md"
  "notes/current-execution-queue-2026-08-10.md"
  "notes/next-steps.md"
  "notes/active-lane-board-2026-08-10.md"
  "notes/cli-4-kickoff-2026-08-10.md"
  "notes/cli-5-kickoff-2026-08-10.md"
  "notes/cli-6-kickoff-2026-08-10.md"
  "notes/recreation-participation-kickoff-2026-08-10.md"
  "notes/handoff-2026-08-10.md"
  "notes/cli-4-5-6-multi-lane-handoff-2026-08-10.md"
  "notes/cli-4-batch-b-handoff-2026-08-10.md"
  "notes/cli-5-batch-d-handoff-2026-08-10.md"
  "notes/cli-6-batch-h-handoff-2026-08-10.md"
  "notes/end-to-end-pursuit-goal-2026-08-10.md"
  "notes/end-to-end-operating-goal-2026-08-10.md"
  "notes/raw-blob-offload-readme-2026-08-10.md"
  "indexes/cli-lane-instructions-2026-08-10.md"
  "analysis/annual-report-stack-alignment-2026-08-09.md"
  "analysis/cross-sector/media-influence-consumer-interface-and-edge-infrastructure-frontier-2026-08-10.md"
  "notes/media-influence-consumer-interface-and-edge-infrastructure-handoff-2026-08-10.md"
  "templates/frontier-lane-master-instruction.md"
  "templates/company-profile.md"
  "templates/company-packet.md"
  "templates/source-ledger.md"
  "templates/industry-brief.md"
  "templates/sector-brief.md"
  "templates/lane-run-template.md"
  "templates/theme-memo.md"
  "templates/status-rubric.md"
  "templates/batch-log-template.md"
  "templates/batch-handoff-template.md"
  "templates/post-batch-integration-checklist.md"
  "analysis/sectors/basic-materials-sector-initial-brief.md"
  "analysis/sectors/cli-4-batch-a-lane-run-2026-08-10.md"
  "analysis/sectors/cli-4-batch-b-lane-run-2026-08-10.md"
  "analysis/sectors/cli-5-batch-a-lane-run-2026-08-10.md"
  "analysis/sectors/cli-5-batch-b-lane-run-2026-08-10.md"
  "analysis/sectors/cli-5-batch-c-lane-run-2026-08-10.md"
  "analysis/sectors/cli-5-batch-d-lane-run-2026-08-10.md"
  "analysis/sectors/consumer-goods-sector-initial-brief.md"
  "analysis/sectors/cli-6-batch-a-lane-run-2026-08-10.md"
  "analysis/sectors/cli-6-batch-b-lane-run-2026-08-10.md"
  "analysis/sectors/cli-6-batch-c-lane-run-2026-08-10.md"
  "analysis/sectors/cli-6-batch-d-lane-run-2026-08-10.md"
  "analysis/sectors/cli-6-batch-e-lane-run-2026-08-10.md"
  "analysis/sectors/cli-6-batch-f-lane-run-2026-08-10.md"
  "analysis/sectors/cli-6-batch-g-lane-run-2026-08-10.md"
  "analysis/sectors/cli-6-batch-h-lane-run-2026-08-10.md"
  "analysis/sectors/financial-sector-initial-brief.md"
  "analysis/sectors/healthcare-sector-initial-brief.md"
  "analysis/sectors/industrial-goods-sector-initial-brief.md"
  "analysis/sectors/recreation-batch-a-lane-run-2026-08-10.md"
  "analysis/sectors/recreation-batch-b-lane-run-2026-08-10.md"
  "analysis/sectors/recreation-batch-c-lane-run-2026-08-10.md"
  "analysis/sectors/real-estate-sector-initial-brief.md"
  "analysis/sectors/services-sector-initial-brief.md"
  "analysis/sectors/technology-sector-initial-brief.md"
  "analysis/sectors/utilities-sector-initial-brief.md"
  "analysis/cross-sector/company-level-strategy-insight-guide-2026-08-10.md"
  "analysis/cross-sector/industry-level-strategy-guide-2026-08-10.md"
  "analysis/cross-sector/concrete-insights-and-curiosity-map-2026-08-10.md"
  "extracted/technology/information-technology-services/dell-technologies-inc/company-packet.md"
  "extracted/technology/information-technology-services/dell-technologies-inc/company-profile.md"
  "extracted/services/catv-systems/comcast-corporation/company-packet.md"
  "extracted/services/advertising-agencies/omnicom-group-inc/company-packet.md"
  "extracted/consumer-goods/photographic-equipment-supplies/gopro-inc/company-packet.md"
  "analysis/cross-sector/metric-glossary-and-watchlist-2026-08-10.md"
  "analysis/cross-sector/thesis-breaker-index-2026-08-10.md"
  "analysis/cross-sector/aha-moments-and-curiosity-questions-2026-08-10.md"
  "analysis/cross-sector/ai-physical-capacity-proof-2026-08-10.md"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md"
  "analysis/cross-sector/hidden-operating-infrastructure-proof-2026-08-10.md"
  "analysis/cross-sector/selective-consumer-proof-2026-08-10.md"
  "analysis/cross-sector/fandom-identity-participation-proof-2026-08-10.md"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md"
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md"
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md"
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md"
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md"
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md"
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md"
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md"
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md"
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md"
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md"
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md"
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md"
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-outside-hospital-proof-2026-08-10.md"
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md"
  "analysis/cross-sector/fill-rate-and-fixed-capacity-absorption-comparison-2026-08-11.md"
  "analysis/cross-sector/backlog-visibility-versus-cash-realization-comparison-2026-08-11.md"
  "analysis/cross-sector/relationship-thickness-inside-travel-and-participation-comparison-2026-08-11.md"
  "analysis/cross-sector/relationship-repair-through-operating-redesign-comparison-2026-08-11.md"
  "analysis/cross-sector/owned-intent-surfaces-and-partner-rent-comparison-2026-08-11.md"
  "analysis/cross-sector/time-compression-and-delegated-everyday-fulfillment-comparison-2026-08-11.md"
  "analysis/cross-sector/embedded-presence-inside-customer-operations-comparison-2026-08-11.md"
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-burden-vs-workflow-comparison-2026-08-11.md"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md"
  "analysis/cross-sector/trust-as-paid-product-proof-2026-08-10.md"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md"
  "analysis/cross-sector/relationship-owner-vs-burden-carrier-proof-2026-08-10.md"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md"
  "analysis/cross-sector/commodity-chain-proof-2026-08-10.md"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md"
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md"
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md"
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md"
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md"
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md"
  "analysis/cross-sector/labor-production-infrastructure-comparison-2026-08-11.md"
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md"
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md"
  "analysis/cross-sector/packaging-as-demand-sensor-and-product-interface-comparison-2026-08-11.md"
  "analysis/cross-sector/low-friction-entrepreneurship-infrastructure-comparison-2026-08-11.md"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md"
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md"
  "analysis/cross-sector/externally-supplied-inventory-and-participation-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/governance-burden-on-participant-platforms-comparison-2026-08-11.md"
  "analysis/cross-sector/replenishment-without-subscription-comparison-2026-08-11.md"
  "analysis/cross-sector/home-as-managed-service-endpoint-comparison-2026-08-11.md"
  "analysis/cross-sector/portfolio-surgery-and-burden-shedding-comparison-2026-08-11.md"
  "analysis/cross-sector/affordability-engineering-and-value-reinvestment-comparison-2026-08-11.md"
  "analysis/cross-sector/ai-readiness-and-usable-context-stack-comparison-2026-08-11.md"
  "analysis/cross-sector/balance-sheet-velocity-and-timing-economics-comparison-2026-08-11.md"
  "analysis/cross-sector/pre-collected-demand-and-obligation-backed-visibility-comparison-2026-08-11.md"
  "analysis/cross-sector/formalized-price-architecture-and-approved-increase-systems-comparison-2026-08-11.md"
  "analysis/cross-sector/policy-distorted-operating-optics-comparison-2026-08-11.md"
  "analysis/cross-sector/taxonomy-blind-spots-proof-2026-08-10.md"
  "analysis/themes/cli-4-5-6-recurring-interface-control-framework-2026-08-10.md"
  "analysis/themes/cli-4-recurring-care-and-workflow-control-framework-2026-08-10.md"
  "analysis/themes/cli-5-ai-capex-and-bottleneck-tolls-2026-08-10.md"
  "analysis/themes/cli-5-control-point-and-chokepoint-framework-2026-08-10.md"
  "analysis/themes/cli-5-software-control-vs-physical-chokepoints-2026-08-10.md"
  "analysis/themes/cli-5-telecom-utility-vs-control-point-economics-2026-08-10.md"
  "analysis/themes/cli-6-trust-intermediation-framework-2026-08-10.md"
  "analysis/themes/capital-intensity-and-investment-concentration-initial-theme-memo.md"
  "analysis/themes/commodity-whiplash-initial-theme-memo.md"
  "analysis/themes/consumer-goods-value-portfolio-initial-theme-memo.md"
  "analysis/themes/cultural-value-trust-and-automation-initial-theme-memo.md"
  "analysis/themes/experience-status-and-community-initial-theme-memo.md"
  "analysis/themes/financial-alternative-manager-fees-and-realizations-initial-theme-memo.md"
  "analysis/themes/financial-asset-management-flows-and-fee-rate-pressure-initial-theme-memo.md"
  "analysis/themes/financial-custody-and-asset-servicing-scale-initial-theme-memo.md"
  "analysis/themes/financial-insurance-underwriting-and-investment-float-initial-theme-memo.md"
  "analysis/themes/financial-large-bank-initial-theme-memo.md"
  "analysis/themes/financial-market-infrastructure-and-risk-transfer-initial-theme-memo.md"
  "analysis/themes/financial-premium-payments-and-membership-initial-theme-memo.md"
  "analysis/themes/financial-ratings-benchmarks-and-data-infrastructure-initial-theme-memo.md"
  "analysis/themes/graying-market-initial-theme-memo.md"
  "analysis/themes/healthcare-frontier-recurring-care-and-therapy-infrastructure-2026-08-10.md"
  "analysis/themes/healthcare-policy-and-portfolio-initial-theme-memo.md"
  "analysis/themes/hospitality-ownership-vs-brand-control-framework-2026-08-10.md"
  "analysis/themes/immigration-squeeze-initial-theme-memo.md"
  "analysis/themes/industrial-automation-and-infrastructure-initial-theme-memo.md"
  "analysis/themes/institutional-operating-infrastructure-initial-theme-memo.md"
  "analysis/themes/labor-intermediation-and-fractional-work-initial-theme-memo.md"
  "analysis/themes/labor-squeeze-initial-theme-memo.md"
  "analysis/themes/loyalty-currencies-partner-monetization-and-deferred-revenue-initial-theme-memo.md"
  "analysis/themes/play-ip-and-fan-participation-framework-2026-08-10.md"
  "analysis/themes/real-estate-reckoning-initial-theme-memo.md"
  "analysis/themes/recreation-participation-demand-framework-2026-08-10.md"
  "analysis/themes/recurring-consumer-interfaces-and-membership-systems-initial-theme-memo.md"
  "analysis/themes/regulation-trust-and-sovereignty-risk-initial-theme-memo.md"
  "analysis/themes/services-freight-brokerage-and-productivity-initial-theme-memo.md"
  "analysis/themes/technology-ai-platform-initial-theme-memo.md"
  "site/index.html"
  "site/concrete-insights.html"
  "site/frontier-companies.html"
  "site/frontier-companies.js"
  "site/site.css"
  "site/viewer.html"
)

required_patterns=(
  "README.md:The packet fields should do explicit analytical work"
  "README.md:Different claim types also need different proof burdens"
  "START-HERE.md:The packet fields should also do explicit analytical work"
  "START-HERE.md:Different claim types also need different proof burdens"
  "templates/lane-run-template.md:The packet fields should also do explicit analytical work"
  "templates/lane-run-template.md:Different claim types also need different proof burdens"
  "templates/lane-run-template.md:Before locking a lane conclusion, write down"
  "templates/lane-run-template.md:Lane claim-to-proof map"
  "templates/lane-run-template.md:Before writing the interpretation, note which packet fields are doing the work"
  "templates/theme-memo.md:Before drafting the memo, decide which packet fields are doing the analytical work"
  "templates/theme-memo.md:Different claim types also need different proof burdens"
  "templates/theme-memo.md:For every serious theme claim, spell out"
  "templates/theme-memo.md:Claim-proof worksheet"
  "templates/theme-memo.md:Packet fields used"
  "templates/status-rubric.md:Proof-discipline check"
  "templates/status-rubric.md:packet-field fit"
  "templates/status-rubric.md:claim-type fit"
  "templates/status-rubric.md:fact-period fit"
  "templates/status-rubric.md:causal fit"
  "templates/status-rubric.md:disconfirming fit"
  "templates/batch-handoff-template.md:which packet fields supplied the strongest lane conclusions"
  "templates/batch-handoff-template.md:what proof burden those strongest claims actually met"
  "templates/batch-handoff-template.md:Strongest claim-to-proof chain"
  "templates/batch-handoff-template.md:exact facts carrying the claim"
  "templates/batch-log-template.md:Even as a lightweight log, it should still preserve the current working proof chain"
  "templates/batch-log-template.md:Working lane claim"
  "templates/post-batch-integration-checklist.md:confirm the packet says what its main fields are proving"
  "templates/post-batch-integration-checklist.md:whether the strongest claims met the right proof burden for their claim type"
  "templates/post-batch-integration-checklist.md:the exact metric or operating fact carrying each major claim"
  "templates/post-batch-integration-checklist.md:what next-filing evidence would weaken or disprove the conclusion"
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Company"
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Lane"
  "notes/insight-extraction-hub-2026-08-11.md:Workflow For A New Theme"
  "notes/insight-extraction-hub-2026-08-11.md:Non-Negotiable Output Shape"
  "notes/insight-extraction-hub-2026-08-11.md:Insight Stack"
  "notes/insight-extraction-hub-2026-08-11.md:Every serious claim should also be reducible to one proof chain"
  "notes/insight-extraction-hub-2026-08-11.md:which packet sections supplied the conclusion"
  "notes/insight-extraction-hub-2026-08-11.md:Before treating any lane summary or proof memo as done, run the skeptical-reader test"
  "notes/insight-extraction-hub-2026-08-11.md:who benefits economically"
  "notes/end-to-end-insight-operator-and-review-brief-2026-08-11.md:The Real Goal"
  "notes/end-to-end-insight-operator-and-review-brief-2026-08-11.md:The Main Insight Types"
  "notes/end-to-end-insight-operator-and-review-brief-2026-08-11.md:The Non-Negotiable Proof Chain"
  "notes/end-to-end-insight-operator-and-review-brief-2026-08-11.md:Operator Loop"
  "notes/end-to-end-insight-operator-and-review-brief-2026-08-11.md:Reviewer Loop"
  "notes/remaining-end-to-end-insight-goal-2026-08-11.md:The Remaining Meaty Goal"
  "notes/remaining-end-to-end-insight-goal-2026-08-11.md:Highest-Value Remaining Batches"
  "notes/remaining-end-to-end-insight-goal-2026-08-11.md:What A Finished Remaining Pass Should Produce"
  "notes/remaining-insight-execution-board-2026-08-11.md:Batch 1: Healthcare Outside The Hospital And Aging Systems"
  "notes/remaining-insight-execution-board-2026-08-11.md:Exact Proof Pages To Strengthen"
  "notes/remaining-insight-execution-board-2026-08-11.md:Common Closeout Requirement"
  "notes/insight-extraction-hub-2026-08-11.md:who carries the burden"
  "notes/master-insight-extraction-goal-2026-08-11.md:No broad claim without concrete filing evidence"
  "notes/master-insight-extraction-goal-2026-08-11.md:The archive should also make the packet-input chain explicit"
  "notes/master-insight-extraction-goal-2026-08-11.md:Skeptical Reader Standard"
  "notes/master-operator-brief-2026-08-10.md:The packet fields should also do explicit analytical work"
  "notes/master-operator-brief-2026-08-10.md:Different claim types also need different proof burdens"
  "notes/master-operator-brief-2026-08-10.md:The practical proof-chain standard is"
  "notes/master-operator-brief-2026-08-10.md:Every serious run should also force the operator to state"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:Master Instruction Block"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:The Required Evidence Chain"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:explicitly name which packet sections are supplying the argument"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:Skeptical Reader Test"
  "notes/end-to-end-insight-master-instruction-2026-08-11.md:What Good Insight Should Sound Like"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md:Reusable Master Instruction"
  "notes/meaty-end-to-end-insight-goal-2026-08-11.md:The standard evidence chain is"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:Step 1: Define The Lane"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:Step 8: Write The Proof Memo"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:exact fact -> exact period -> plain-English meaning -> causal explanation -> alternative explanation -> disconfirming next-filing test"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:consumer behavior shift"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:Start by naming which packet inputs are supporting the lane read"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:run a direct reader test"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:relationship-owner versus burden-carrier split"
  "notes/lane-end-to-end-execution-runbook-2026-08-11.md:consumer, cultural, societal, industrial, technical, or capital-structure meaning is explicit"
  "notes/insight-extraction-templates-2026-08-11.md:Company Packet Template"
  "notes/insight-extraction-templates-2026-08-11.md:Insight Stack"
  "notes/insight-extraction-templates-2026-08-11.md:Insight Stack Across The Lane"
  "notes/insight-extraction-templates-2026-08-11.md:Packet Inputs Used For Lane Insight"
  "notes/insight-extraction-templates-2026-08-11.md:Packet Inputs Used"
  "notes/insight-extraction-templates-2026-08-11.md:Reader Test"
  "notes/insight-extraction-templates-2026-08-11.md:Beneficiaries And Burden Carriers"
  "notes/insight-extraction-templates-2026-08-11.md:Why This Matters Now"
  "notes/insight-extraction-templates-2026-08-11.md:Run Closeout Template"
  "notes/insight-completion-rubric-2026-08-11.md:Company Packet Rubric"
  "notes/insight-completion-rubric-2026-08-11.md:The strongest version of that path is"
  "notes/insight-completion-rubric-2026-08-11.md:Fact-Period-Causal Fit"
  "notes/insight-completion-rubric-2026-08-11.md:Lane Summary Rubric"
  "notes/insight-completion-rubric-2026-08-11.md:Proof Memo Rubric"
  "notes/insight-completion-rubric-2026-08-11.md:Skeptical Reader Test"
  "notes/insight-completion-rubric-2026-08-11.md:Fast Failure Tests"
  "notes/insight-completion-rubric-2026-08-11.md:it never says which packet inputs supplied the lane or memo conclusion"
  "notes/insight-completion-rubric-2026-08-11.md:capital pattern without saying how the filing evidence supports it"
  "notes/insight-completion-rubric-2026-08-11.md:who benefits and who carries burden"
  "notes/insight-artifact-manifest-2026-08-11.md:Required Insight System Layers"
  "notes/insight-artifact-manifest-2026-08-11.md:Required Proof Chain"
  "notes/insight-artifact-manifest-2026-08-11.md:Reusable Note Layer"
  "notes/insight-artifact-manifest-2026-08-11.md:Standardization Boundary"
  "notes/insight-artifact-manifest-2026-08-11.md:Proof Memo Inventory"
  "notes/insight-artifact-manifest-2026-08-11.md:Raw-evidence governance"
  "notes/raw-evidence-link-policy-2026-08-11.md:Packet Inputs Used"
  "notes/raw-evidence-link-policy-2026-08-11.md:Skeptical Reader Test"
  "notes/legacy-root-reference-audit-2026-08-11.md:Packet Inputs Used"
  "notes/legacy-root-reference-audit-2026-08-11.md:Skeptical Reader Test"
  "notes/insight-note-standardization-cutoff-2026-08-11.md:Deliberate Cutoff"
  "notes/insight-note-standardization-cutoff-2026-08-11.md:Current remaining count at the cutoff"
  "notes/insight-driven-next-lane-queue-2026-08-11.md:Best Immediate Next Move"
  "notes/insight-driven-next-lane-queue-2026-08-11.md:Before starting a queue item, identify which packet inputs will matter most"
  "notes/insight-driven-next-lane-queue-2026-08-11.md:the best alternative explanation the batch might overturn or confirm"
  "notes/insight-driven-next-lane-queue-2026-08-11.md:Skeptical Reader Gate"
  "notes/current-execution-queue-2026-08-10.md:Before opening the batch, decide which packet fields should do the work"
  "notes/current-execution-queue-2026-08-10.md:Also decide what kind of claim the lane is meant to sharpen"
  "notes/current-execution-queue-2026-08-10.md:the best alternative explanation still in play"
  "notes/next-steps.md:Before writing the interpretation, decide what the packet fields are supposed to prove"
  "notes/next-steps.md:Also decide which kind of claim the company should strengthen"
  "notes/next-steps.md:the best alternative explanation still in play"
  "notes/active-lane-board-2026-08-10.md:Packet Inputs Used"
  "notes/active-lane-board-2026-08-10.md:Default interpretive window"
  "notes/active-lane-board-2026-08-10.md:Skeptical Reader Test"
  "notes/cli-4-kickoff-2026-08-10.md:Packet Inputs Used"
  "notes/cli-4-kickoff-2026-08-10.md:Cross-company themes to extract"
  "notes/cli-4-kickoff-2026-08-10.md:Working proof-chain setup before starting"
  "notes/cli-4-kickoff-2026-08-10.md:Skeptical Reader Test"
  "notes/cli-5-kickoff-2026-08-10.md:Packet Inputs Used"
  "notes/cli-5-kickoff-2026-08-10.md:Cross-company themes to extract"
  "notes/cli-5-kickoff-2026-08-10.md:Working proof-chain setup before starting"
  "notes/cli-5-kickoff-2026-08-10.md:Skeptical Reader Test"
  "notes/cli-6-kickoff-2026-08-10.md:Packet Inputs Used"
  "notes/cli-6-kickoff-2026-08-10.md:Cross-company themes to extract"
  "notes/cli-6-kickoff-2026-08-10.md:Working proof-chain setup before starting"
  "notes/cli-6-kickoff-2026-08-10.md:Skeptical Reader Test"
  "notes/recreation-participation-kickoff-2026-08-10.md:Packet Inputs Used"
  "notes/recreation-participation-kickoff-2026-08-10.md:Cross-company themes to extract"
  "notes/recreation-participation-kickoff-2026-08-10.md:Working proof-chain setup before starting"
  "notes/recreation-participation-kickoff-2026-08-10.md:Skeptical Reader Test"
  "notes/handoff-2026-08-10.md:Current authoritative checkpoint"
  "notes/cli-4-5-6-multi-lane-handoff-2026-08-10.md:Strongest cross-lane signals"
  "notes/cli-4-batch-b-handoff-2026-08-10.md:Strongest cross-company signals"
  "notes/cli-5-batch-d-handoff-2026-08-10.md:Strongest cross-company signals"
  "notes/cli-6-batch-h-handoff-2026-08-10.md:Strongest cross-company signals"
  "notes/raw-blob-offload-readme-2026-08-10.md:Resolving packet evidence links"
  "notes/raw-blob-offload-readme-2026-08-10.md:Skeptical Reader Test"
  "indexes/cli-lane-instructions-2026-08-10.md:Master pursuit goal"
  "indexes/cli-lane-instructions-2026-08-10.md:Interpretation here means identifying the lived systems underneath the filings"
  "indexes/cli-lane-instructions-2026-08-10.md:Standard for every CLI lane"
  "analysis/cross-sector/media-influence-consumer-interface-and-edge-infrastructure-frontier-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/media-influence-consumer-interface-and-edge-infrastructure-frontier-2026-08-10.md:Required evidence window for all eventual packet work"
  "notes/end-to-end-pursuit-goal-2026-08-10.md:Those packet inputs should also be read as proof tools"
  "notes/end-to-end-pursuit-goal-2026-08-10.md:Different claim types also need different proof burdens"
  "notes/end-to-end-operating-goal-2026-08-10.md:The packet fields should also do explicit analytical work"
  "notes/end-to-end-operating-goal-2026-08-10.md:Different claim types also need different proof burdens"
  "templates/frontier-lane-master-instruction.md:The packet fields should also do explicit analytical work"
  "templates/frontier-lane-master-instruction.md:Different claim types also need different proof burdens"
  "templates/frontier-lane-master-instruction.md:which packet fields are actually doing the analytical work"
  "templates/company-profile.md:Use the profile as a quick-read proof surface, not just a directory card"
  "templates/company-profile.md:Claim-to-proof summary"
  "templates/company-packet.md:Use the packet fields as analytical inputs, not just headings"
  "templates/company-packet.md:Different claim types also need different proof burdens"
  "templates/company-packet.md:For every non-trivial claim, write down"
  "templates/company-packet.md:Claim-to-proof map"
  "templates/source-ledger.md:The ledger should make it easy to answer"
  "templates/source-ledger.md:Claim coverage map"
  "templates/industry-brief.md:Before writing the brief, name the working proof chain"
  "templates/industry-brief.md:Claim-to-proof map"
  "templates/sector-brief.md:Before writing the brief, name the proof chain"
  "templates/sector-brief.md:Claim-to-proof map"
  "analysis/annual-report-stack-alignment-2026-08-09.md:Packet Inputs Used"
  "analysis/annual-report-stack-alignment-2026-08-09.md:Skeptical Reader Test"
  "analysis/sectors/basic-materials-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/basic-materials-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/sectors/cli-4-batch-a-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-4-batch-a-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-4-batch-b-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-4-batch-b-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-5-batch-a-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-5-batch-a-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-5-batch-b-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-5-batch-b-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-5-batch-c-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-5-batch-c-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-5-batch-d-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-5-batch-d-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/consumer-goods-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/consumer-goods-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/sectors/cli-6-batch-a-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-6-batch-a-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-6-batch-b-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-6-batch-b-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-6-batch-c-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-6-batch-c-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-6-batch-d-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-6-batch-d-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-6-batch-e-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-6-batch-e-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-6-batch-f-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-6-batch-f-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-6-batch-g-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-6-batch-g-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/cli-6-batch-h-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/cli-6-batch-h-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/financial-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/financial-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/sectors/healthcare-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/healthcare-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/sectors/industrial-goods-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/industrial-goods-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/sectors/recreation-batch-a-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/recreation-batch-a-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/recreation-batch-b-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/recreation-batch-b-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/recreation-batch-c-lane-run-2026-08-10.md:Packet Inputs Used"
  "analysis/sectors/recreation-batch-c-lane-run-2026-08-10.md:Skeptical Reader Test"
  "analysis/sectors/real-estate-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/real-estate-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/sectors/services-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/services-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/sectors/technology-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/technology-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/sectors/utilities-sector-initial-brief.md:Packet Inputs Used"
  "analysis/sectors/utilities-sector-initial-brief.md:Skeptical Reader Test"
  "analysis/cross-sector/company-level-strategy-insight-guide-2026-08-10.md:Every serious company-level conclusion should also be reducible to one proof chain"
  "analysis/cross-sector/company-level-strategy-insight-guide-2026-08-10.md:What Is The Exact Proof Chain?"
  "analysis/cross-sector/industry-level-strategy-guide-2026-08-10.md:Every serious lane conclusion should also be reducible to one proof chain"
  "analysis/cross-sector/industry-level-strategy-guide-2026-08-10.md:Lane Claim-To-Proof Worksheet"
  "analysis/cross-sector/thesis-breaker-index-2026-08-10.md:A good thesis breaker should still preserve the same full chain"
  "extracted/technology/information-technology-services/dell-technologies-inc/company-packet.md:Dell Technologies Inc. Company Packet"
  "extracted/technology/information-technology-services/dell-technologies-inc/company-profile.md:Dell Technologies Inc."
  "extracted/services/catv-systems/comcast-corporation/company-packet.md:Comcast Corporation Company Packet"
  "extracted/services/advertising-agencies/omnicom-group-inc/company-packet.md:Omnicom Group Inc. Company Packet"
  "extracted/consumer-goods/photographic-equipment-supplies/gopro-inc/company-packet.md:GoPro, Inc. Company Packet"
  "site/index.html:Operator-ready master instruction"
  "site/index.html:Operator and review brief"
  "site/index.html:Remaining end-to-end insight goal"
  "site/index.html:Start Standard"
  "site/index.html:proof chain, operator loop, and reviewer loop"
  "site/index.html:what substantive archive work is still left"
  "site/index.html:The strongest pages should also make the proof chain explicit"
  "site/index.html:Raw Evidence Governance"
  "site/index.html:Every serious claim should still be reducible to one auditable sentence"
  "site/index.html:resolve-offloaded-raw-path.py"
  "site/index.html:verify-raw-evidence-governance.sh"
  "site/concrete-insights.html:Operator-ready master instruction"
  "site/concrete-insights.html:Operator and review brief"
  "site/concrete-insights.html:Remaining end-to-end insight goal"
  "site/concrete-insights.html:How To Read An Insight Here"
  "site/concrete-insights.html:operator loop for producing the work, and the reviewer loop for deciding whether it is actually done"
  "site/concrete-insights.html:What Counts As Concrete Support"
  "site/concrete-insights.html:Raw Evidence Audit Layer"
  "site/concrete-insights.html:resolve-offloaded-raw-path.py"
  "site/concrete-insights.html:verify-raw-evidence-governance.sh"
  "site/frontier-companies.html:Completed Companies"
  "site/frontier-companies.html:Source ledger"
  "site/frontier-companies.js:window.frontierCompanies = ["
  "site/frontier-companies.js:name: \"Attention and influence\""
  "site/site.css::root {"
  "site/site.css:.company-grid"
  "site/viewer.html:Markdown Viewer"
  "site/viewer.html:Missing <code>file</code> query parameter."
  "analysis/cross-sector/company-level-strategy-insight-guide-2026-08-10.md:The company-level note should also say which packet sections are doing the work"
  "analysis/cross-sector/company-level-strategy-insight-guide-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/industry-level-strategy-guide-2026-08-10.md:Before writing the lane interpretation, name which packet inputs are supporting it"
  "analysis/cross-sector/industry-level-strategy-guide-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/concrete-insights-and-curiosity-map-2026-08-10.md:Packet Inputs That Should Feed This Page"
  "analysis/cross-sector/concrete-insights-and-curiosity-map-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/aha-moments-and-curiosity-questions-2026-08-10.md:Use it as a synthesis layer, not a freeform idea list"
  "analysis/cross-sector/aha-moments-and-curiosity-questions-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/thesis-breaker-index-2026-08-10.md:The thesis-breaker layer should stay tied to the same packet evidence as the main insight"
  "analysis/cross-sector/thesis-breaker-index-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/ai-physical-capacity-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/ai-physical-capacity-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/healthcare-outside-hospital-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/healthcare-outside-hospital-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/hidden-operating-infrastructure-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/hidden-operating-infrastructure-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/selective-consumer-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/selective-consumer-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/fandom-identity-participation-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/fandom-identity-participation-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/trust-as-paid-product-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/trust-as-paid-product-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/relationship-owner-vs-burden-carrier-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/relationship-owner-vs-burden-carrier-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/taxonomy-blind-spots-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/taxonomy-blind-spots-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/cli-4-5-6-recurring-interface-control-framework-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/cli-4-5-6-recurring-interface-control-framework-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/cli-4-recurring-care-and-workflow-control-framework-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/cli-4-recurring-care-and-workflow-control-framework-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/cli-5-ai-capex-and-bottleneck-tolls-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/cli-5-ai-capex-and-bottleneck-tolls-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/cli-5-control-point-and-chokepoint-framework-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/cli-5-control-point-and-chokepoint-framework-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/cli-5-software-control-vs-physical-chokepoints-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/cli-5-software-control-vs-physical-chokepoints-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/cli-5-telecom-utility-vs-control-point-economics-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/cli-5-telecom-utility-vs-control-point-economics-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/cli-6-trust-intermediation-framework-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/cli-6-trust-intermediation-framework-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/capital-intensity-and-investment-concentration-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/capital-intensity-and-investment-concentration-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/commodity-whiplash-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/commodity-whiplash-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/consumer-goods-value-portfolio-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/consumer-goods-value-portfolio-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/cultural-value-trust-and-automation-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/cultural-value-trust-and-automation-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/experience-status-and-community-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/experience-status-and-community-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/financial-alternative-manager-fees-and-realizations-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/financial-alternative-manager-fees-and-realizations-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/financial-asset-management-flows-and-fee-rate-pressure-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/financial-asset-management-flows-and-fee-rate-pressure-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/financial-custody-and-asset-servicing-scale-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/financial-custody-and-asset-servicing-scale-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/financial-insurance-underwriting-and-investment-float-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/financial-insurance-underwriting-and-investment-float-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/financial-large-bank-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/financial-large-bank-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/financial-market-infrastructure-and-risk-transfer-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/financial-market-infrastructure-and-risk-transfer-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/financial-premium-payments-and-membership-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/financial-premium-payments-and-membership-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/financial-ratings-benchmarks-and-data-infrastructure-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/financial-ratings-benchmarks-and-data-infrastructure-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/graying-market-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/graying-market-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/healthcare-frontier-recurring-care-and-therapy-infrastructure-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/healthcare-frontier-recurring-care-and-therapy-infrastructure-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/healthcare-policy-and-portfolio-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/healthcare-policy-and-portfolio-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/hospitality-ownership-vs-brand-control-framework-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/hospitality-ownership-vs-brand-control-framework-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/immigration-squeeze-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/immigration-squeeze-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/industrial-automation-and-infrastructure-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/industrial-automation-and-infrastructure-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/institutional-operating-infrastructure-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/institutional-operating-infrastructure-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/labor-intermediation-and-fractional-work-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/labor-intermediation-and-fractional-work-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/labor-squeeze-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/labor-squeeze-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/loyalty-currencies-partner-monetization-and-deferred-revenue-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/loyalty-currencies-partner-monetization-and-deferred-revenue-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/play-ip-and-fan-participation-framework-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/play-ip-and-fan-participation-framework-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/real-estate-reckoning-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/real-estate-reckoning-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/recreation-participation-demand-framework-2026-08-10.md:Packet Inputs Used"
  "analysis/themes/recreation-participation-demand-framework-2026-08-10.md:Skeptical Reader Test"
  "analysis/themes/recurring-consumer-interfaces-and-membership-systems-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/recurring-consumer-interfaces-and-membership-systems-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/regulation-trust-and-sovereignty-risk-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/regulation-trust-and-sovereignty-risk-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/services-freight-brokerage-and-productivity-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/services-freight-brokerage-and-productivity-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/themes/technology-ai-platform-initial-theme-memo.md:Packet Inputs Used"
  "analysis/themes/technology-ai-platform-initial-theme-memo.md:Skeptical Reader Test"
  "analysis/cross-sector/commodity-chain-proof-2026-08-10.md:Packet Inputs Used"
  "analysis/cross-sector/commodity-chain-proof-2026-08-10.md:Skeptical Reader Test"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/time-compression-and-delegated-everyday-fulfillment-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/time-compression-and-delegated-everyday-fulfillment-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/relationship-thickness-inside-travel-and-participation-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/relationship-thickness-inside-travel-and-participation-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Clean Capture Versus Burden Carrier Map"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Backlog Conversion Analysis"
  "analysis/cross-sector/ai-capacity-burden-carrier-comparison-2026-08-11.md:Power And Skilled-Labor Bottleneck"
  "analysis/cross-sector/ai-readiness-and-usable-context-stack-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/ai-readiness-and-usable-context-stack-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/affordability-engineering-and-value-reinvestment-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/affordability-engineering-and-value-reinvestment-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/backlog-visibility-versus-cash-realization-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/backlog-visibility-versus-cash-realization-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/balance-sheet-velocity-and-timing-economics-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/balance-sheet-velocity-and-timing-economics-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/embedded-presence-inside-customer-operations-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/embedded-presence-inside-customer-operations-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/fill-rate-and-fixed-capacity-absorption-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/fill-rate-and-fixed-capacity-absorption-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/healthcare-burden-vs-workflow-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/healthcare-burden-vs-workflow-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/owned-intent-surfaces-and-partner-rent-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/owned-intent-surfaces-and-partner-rent-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/pre-collected-demand-and-obligation-backed-visibility-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/pre-collected-demand-and-obligation-backed-visibility-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/portfolio-surgery-and-burden-shedding-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/portfolio-surgery-and-burden-shedding-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/replenishment-without-subscription-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/replenishment-without-subscription-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:Packet Inputs Used"
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:Skeptical Reader Test"
  "analysis/cross-sector/healthcare-burden-vs-workflow-comparison-2026-08-11.md:Burden Versus Cleaner Workflow Map"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Recurring Care Workflow Map"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Diagnostic Information Versus Therapy Delivery Distinction"
  "analysis/cross-sector/healthcare-testing-distribution-delivery-comparison-2026-08-11.md:Distribution Versus Installed Workflow Distinction"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Occasion Versus Routine Demand Map"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Brand Relationship Versus Inventory And Support Burden"
  "analysis/cross-sector/recreation-lifestyle-occasion-demand-comparison-2026-08-11.md:Queue Status"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:Paid Relationship Map"
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:“Subscription” is too blunt a category."
  "analysis/cross-sector/paid-relationship-and-habit-loop-comparison-2026-08-11.md:The best paid relationships reduce friction before the next decision."
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Status And Wallet Map"
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Status systems get stronger when they capture spend beyond the core activity."
  "analysis/cross-sector/status-wallet-and-default-spend-comparison-2026-08-11.md:Co-brand and partner structures can be as important as direct customer behavior."
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:Continuity Versus Upgrade Map"
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:Maintenance is not a narrow industrial idea."
  "analysis/cross-sector/continuity-and-maintenance-economics-comparison-2026-08-11.md:The stronger conclusion is that a large part of the modern economy is built around continuity spending."
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:Overhead And Control-Plane Map"
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:Complexity itself is becoming a monetizable demand driver."
  "analysis/cross-sector/institutional-overhead-and-control-plane-comparison-2026-08-11.md:When the cost of disorder rises, the company that reduces disorder can become a durable toll collector."
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:Coordination Toll Map"
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:Fragmented systems create attractive coordination tolls."
  "analysis/cross-sector/coordination-toll-without-asset-ownership-comparison-2026-08-11.md:When a market is fragmented and the customer needs help navigating it repeatedly, the coordination layer can become more valuable than a large share of the underlying asset base."
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed Loop Versus Open Routing Map"
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed loops and open routers both sit in the middle, but they monetize different customer behavior."
  "analysis/cross-sector/closed-loop-ecosystem-versus-open-routing-comparison-2026-08-11.md:Closed loops maximize retained behavior, while open routers maximize useful choice."
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:Access System Map"
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:Access can be more important than ownership when repeat behavior matters."
  "analysis/cross-sector/access-instead-of-ownership-comparison-2026-08-11.md:When repeat use matters more than one-time ownership, the company that controls access can build a stronger relationship than the company selling isolated transactions."
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md:Self-Maintenance Map"
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md:Confidence is an economic variable."
  "analysis/cross-sector/self-maintenance-and-confidence-spend-comparison-2026-08-11.md:When a business helps the customer stay ready, comfortable, or confident in repeatable ways, the spending can remain resilient even when consumers become more selective elsewhere."
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md:Discovery And Decision-Reduction Map"
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md:Abundance creates a new layer of economic value."
  "analysis/cross-sector/discovery-and-decision-reduction-comparison-2026-08-11.md:When supply gets too broad for the customer to sort efficiently alone, the interface that reduces choice overload can become one of the strongest profit pools in the system."
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md:Relationship-Thickening Map"
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md:The first customer relationship is often only the start of the business."
  "analysis/cross-sector/relationship-thickening-and-second-layer-monetization-comparison-2026-08-11.md:Once a company owns a durable customer relationship, the next big economic unlock often comes from adding a second layer on top of it rather than only growing the original product."
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md:Standardization Map"
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md:Simplification is a real product, not a byproduct."
  "analysis/cross-sector/standardization-and-simplification-as-product-comparison-2026-08-11.md:When complexity becomes painful enough, the company that makes the workflow more uniform can become one of the most durable toll collectors in the system."
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md:Delegation Map"
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md:These companies are often selling relief, not just output."
  "analysis/cross-sector/delegated-operations-and-outsourced-complexity-comparison-2026-08-11.md:They are selling fewer broken handoffs."
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md:Failure-Avoidance Map"
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md:Prevention spending is often easier to justify than repair spending."
  "analysis/cross-sector/failure-avoidance-and-uptime-economics-comparison-2026-08-11.md:They are core economic layers."
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md:Compliance Map"
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md:Compliance demand is often more recurring than preference-based demand."
  "analysis/cross-sector/compliance-and-mandated-spend-economics-comparison-2026-08-11.md:It is also a demand engine."
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md:Labor-Scarcity Map"
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md:Backlog and demand are only meaningful if qualified labor exists to convert them."
  "analysis/cross-sector/specialist-labor-and-certified-capacity-comparison-2026-08-11.md:That is why specialist labor should be treated as a core economic layer, not just as an operating headache."
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md:Density Map"
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md:Density often looks boring until it compounds."
  "analysis/cross-sector/density-and-local-coverage-as-moat-comparison-2026-08-11.md:the dense network can become the real product."
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md:Adaptation Map"
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md:Institutions increasingly buy adaptation capacity, not just outside opinions."
  "analysis/cross-sector/institutional-adaptation-and-capability-outsourcing-comparison-2026-08-11.md:It is outsourced adaptation."
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Aging Burden Map"
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Home is becoming the default setting for more of the aging system."
  "analysis/cross-sector/aging-as-operating-reality-comparison-2026-08-11.md:Aging produces more logistics than most demographic language suggests."
  "analysis/cross-sector/fill-rate-and-fixed-capacity-absorption-comparison-2026-08-11.md:Fill-Rate And Capacity Map"
  "analysis/cross-sector/fill-rate-and-fixed-capacity-absorption-comparison-2026-08-11.md:Small fill-rate changes matter because the cost base is already there."
  "analysis/cross-sector/fill-rate-and-fixed-capacity-absorption-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's most repeatable operating patterns is fixed-capacity absorption."
  "analysis/cross-sector/backlog-visibility-versus-cash-realization-comparison-2026-08-11.md:Backlog Conversion Map"
  "analysis/cross-sector/backlog-visibility-versus-cash-realization-comparison-2026-08-11.md:Backlog is a visibility tool, not a finished result."
  "analysis/cross-sector/backlog-visibility-versus-cash-realization-comparison-2026-08-11.md:The stronger conclusion is that backlog is one of the archive's most useful but most misread signals."
  "analysis/cross-sector/relationship-thickness-inside-travel-and-participation-comparison-2026-08-11.md:Relationship-Thickness Map"
  "analysis/cross-sector/relationship-thickness-inside-travel-and-participation-comparison-2026-08-11.md:Travel demand is one thing. Relationship thickness is another."
  "analysis/cross-sector/relationship-thickness-inside-travel-and-participation-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's most important distinctions is not just who serves the traveler or participant."
  "analysis/cross-sector/relationship-repair-through-operating-redesign-comparison-2026-08-11.md:Relationship-Repair Map"
  "analysis/cross-sector/relationship-repair-through-operating-redesign-comparison-2026-08-11.md:mature consumer and service businesses can no longer assume habit is enough"
  "analysis/cross-sector/relationship-repair-through-operating-redesign-comparison-2026-08-11.md:repair the experience first so the recurring relationship becomes worth more again"
  "analysis/cross-sector/owned-intent-surfaces-and-partner-rent-comparison-2026-08-11.md:Intent-Surface Map"
  "analysis/cross-sector/owned-intent-surfaces-and-partner-rent-comparison-2026-08-11.md:First-party intent is becoming rentable infrastructure."
  "analysis/cross-sector/owned-intent-surfaces-and-partner-rent-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's best recurring patterns is the rise of owned intent surfaces."
  "analysis/cross-sector/time-compression-and-delegated-everyday-fulfillment-comparison-2026-08-11.md:Time-Compression Map"
  "analysis/cross-sector/time-compression-and-delegated-everyday-fulfillment-comparison-2026-08-11.md:time compression itself is becoming a monetizable layer"
  "analysis/cross-sector/time-compression-and-delegated-everyday-fulfillment-comparison-2026-08-11.md:time-saving has become a real economic product"
  "analysis/cross-sector/embedded-presence-inside-customer-operations-comparison-2026-08-11.md:Embedded-Presence Map"
  "analysis/cross-sector/embedded-presence-inside-customer-operations-comparison-2026-08-11.md:Embedded presence is a stronger moat than simple availability."
  "analysis/cross-sector/embedded-presence-inside-customer-operations-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's quiet but important recurring patterns is embedded operating presence."
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md:Beauty-Interface Map"
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md:The beauty winner is often the company that shortens the trend-to-purchase cycle."
  "analysis/cross-sector/beauty-discovery-and-data-interface-comparison-2026-08-11.md:The stronger conclusion is that beauty is one of the archive's clearest examples of a consumer category turning into a discovery-and-data interface."
  "analysis/cross-sector/healthcare-outside-hospital-proof-2026-08-10.md:healthcare-burden-vs-workflow-comparison-2026-08-11.md"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Standards Versus Vendors Distinction"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Proof Layer Economics"
  "analysis/cross-sector/trust-proof-measurement-security-comparison-2026-08-11.md:Queue Status"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Property Burden Map"
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Senior housing breaks the simple asset-light rule."
  "analysis/cross-sector/relationship-ownership-versus-property-burden-comparison-2026-08-11.md:Data centers show when property becomes infrastructure instead of generic real estate."
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Chain-By-Chain Comparison"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Input Cost Versus End-Market Demand Map"
  "analysis/cross-sector/commodity-chain-comparison-2026-08-11.md:Tariff And Policy Watchlist"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:Attention Owner Versus Attention Helper Comparison"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:Trust Versus Reach Distinction"
  "analysis/cross-sector/media-attention-helper-comparison-2026-08-11.md:AI Impact Curiosity Section"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Role Map"
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Owning attention is not the same as owning the money flow."
  "analysis/cross-sector/media-owner-helper-economics-comparison-2026-08-11.md:Commerce intent is becoming part of the media stack."
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Interface Ownership Map"
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Asset-light does not mean low burden. It means the burden moves."
  "analysis/cross-sector/interface-ownership-and-demand-orchestration-comparison-2026-08-11.md:Local commerce is becoming more like operating infrastructure."
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md:Point-Of-Use Control Map"
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md:The most defensible part of the system is often the part that the user actually touches."
  "analysis/cross-sector/point-of-use-control-and-qualified-interface-comparison-2026-08-11.md:The stronger conclusion is that some of the best businesses in the archive win by owning the qualified point of use."
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md:Narrow Chokepoint Map"
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md:A small layer can control a much larger economic system."
  "analysis/cross-sector/narrow-chokepoint-and-disproportionate-consequence-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's best recurring patterns is not scale alone."
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md:Reapproval Friction Map"
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md:Switching cost is often too vague a phrase."
  "analysis/cross-sector/qualification-validation-and-reapproval-friction-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's best businesses are protected by the cost of reopening a trusted system."
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md:Pull-Through Map"
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md:The initial sale often understates the real business."
  "analysis/cross-sector/installed-base-and-pull-through-economics-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's best businesses are not one-time product businesses at all."
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md:Accepted-Record Map"
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md:The valuable layer is often the accepted record, not only the workflow tool."
  "analysis/cross-sector/accepted-record-and-auditable-workflow-control-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's best recurring businesses own the accepted record inside a workflow."
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md:Frontline-Visibility Map"
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md:A lot of value sits in making work legible at the frontline."
  "analysis/cross-sector/frontline-visibility-and-executable-workflow-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's underappreciated economic layers is frontline visibility."
  "analysis/cross-sector/labor-production-infrastructure-comparison-2026-08-11.md:Labor-Production Map"
  "analysis/cross-sector/labor-production-infrastructure-comparison-2026-08-11.md:Labor shortages create demand one step upstream from hiring."
  "analysis/cross-sector/labor-production-infrastructure-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's underappreciated growth systems is labor production itself."
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md:Machine-Readable-State Map"
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md:Many high-value systems begin by making reality legible."
  "analysis/cross-sector/machine-readable-operating-state-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's quieter but important economic layers is standardized operating state."
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md:Decision-Authority Map"
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md:Institutions often pay to narrow the choice set before they act."
  "analysis/cross-sector/outsourced-judgment-and-benchmark-authority-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's most important financial layers is outsourced decision authority."
  "analysis/cross-sector/packaging-as-demand-sensor-and-product-interface-comparison-2026-08-11.md:Packaging-Economics Map"
  "analysis/cross-sector/packaging-as-demand-sensor-and-product-interface-comparison-2026-08-11.md:Packaging is often a better read on real demand than the shelf story alone."
  "analysis/cross-sector/packaging-as-demand-sensor-and-product-interface-comparison-2026-08-11.md:The stronger conclusion is that packaging is one of the archive's better hidden readouts on both demand quality and physical burden."
  "analysis/cross-sector/low-friction-entrepreneurship-infrastructure-comparison-2026-08-11.md:Entrepreneurship-Infrastructure Map"
  "analysis/cross-sector/low-friction-entrepreneurship-infrastructure-comparison-2026-08-11.md:The stronger conclusion is that a large part of modern entrepreneurship now depends on access to infrastructure"
  "analysis/cross-sector/low-friction-entrepreneurship-infrastructure-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md:Commitment-Friction Map"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md:The stronger conclusion is that a growing part of the economy is being optimized around commitment friction"
  "analysis/cross-sector/deferred-commitment-and-conversion-infrastructure-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md:Intent-Capture Map"
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md:The stronger conclusion is that one of the next important economic layers in commerce is not just who owns the destination site."
  "analysis/cross-sector/intent-capture-and-agentic-commerce-interface-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/externally-supplied-inventory-and-participation-economics-comparison-2026-08-11.md:External-Supply Map"
  "analysis/cross-sector/externally-supplied-inventory-and-participation-economics-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's recurring economic patterns is the rise of businesses whose real inventory is supplied from the outside."
  "analysis/cross-sector/externally-supplied-inventory-and-participation-economics-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/governance-burden-on-participant-platforms-comparison-2026-08-11.md:Governance-Burden Map"
  "analysis/cross-sector/governance-burden-on-participant-platforms-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's most scalable participant platforms are really governance systems in disguise."
  "analysis/cross-sector/governance-burden-on-participant-platforms-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/replenishment-without-subscription-comparison-2026-08-11.md:Replenishment Map"
  "analysis/cross-sector/replenishment-without-subscription-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's better hidden repeat-economics patterns is replenishment without subscription."
  "analysis/cross-sector/replenishment-without-subscription-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/home-as-managed-service-endpoint-comparison-2026-08-11.md:Home-Endpoint Map"
  "analysis/cross-sector/home-as-managed-service-endpoint-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's clearer cross-sector shifts is the rise of the home as a managed service endpoint."
  "analysis/cross-sector/home-as-managed-service-endpoint-comparison-2026-08-11.md:When the household becomes the service endpoint, the winning company is often the one that can keep showing up there reliably without letting the burden stack overwhelm the relationship."
  "analysis/cross-sector/portfolio-surgery-and-burden-shedding-comparison-2026-08-11.md:Simplification Map"
  "analysis/cross-sector/portfolio-surgery-and-burden-shedding-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's more important repeating strategy patterns is portfolio surgery and burden shedding."
  "analysis/cross-sector/portfolio-surgery-and-burden-shedding-comparison-2026-08-11.md:quality is often created by subtraction"
  "analysis/cross-sector/affordability-engineering-and-value-reinvestment-comparison-2026-08-11.md:Value-Repair Map"
  "analysis/cross-sector/affordability-engineering-and-value-reinvestment-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's more important cross-sector operating patterns is affordability engineering and value reinvestment."
  "analysis/cross-sector/affordability-engineering-and-value-reinvestment-comparison-2026-08-11.md:protecting the habit or the closing can matter more than defending the old margin structure."
  "analysis/cross-sector/ai-readiness-and-usable-context-stack-comparison-2026-08-11.md:AI-Readiness Stack Map"
  "analysis/cross-sector/ai-readiness-and-usable-context-stack-comparison-2026-08-11.md:The stronger conclusion is that one of the archive's clearest AI-era patterns is the rise of the AI-readiness stack."
  "analysis/cross-sector/ai-readiness-and-usable-context-stack-comparison-2026-08-11.md:many of the most important AI profit pools may sit in the layers that make AI usable before the model produces the answer."
  "analysis/cross-sector/balance-sheet-velocity-and-timing-economics-comparison-2026-08-11.md:Balance-Sheet Velocity Map"
  "analysis/cross-sector/balance-sheet-velocity-and-timing-economics-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's most important businesses are not only selling product, service, or access."
  "analysis/cross-sector/balance-sheet-velocity-and-timing-economics-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/pre-collected-demand-and-obligation-backed-visibility-comparison-2026-08-11.md:Pre-Collected Demand Map"
  "analysis/cross-sector/pre-collected-demand-and-obligation-backed-visibility-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's better businesses are not only recurring."
  "analysis/cross-sector/pre-collected-demand-and-obligation-backed-visibility-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/formalized-price-architecture-and-approved-increase-systems-comparison-2026-08-11.md:Price-Architecture Map"
  "analysis/cross-sector/formalized-price-architecture-and-approved-increase-systems-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's better businesses are not only businesses with pricing power."
  "analysis/cross-sector/formalized-price-architecture-and-approved-increase-systems-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "analysis/cross-sector/policy-distorted-operating-optics-comparison-2026-08-11.md:Distorted-Quarter Map"
  "analysis/cross-sector/policy-distorted-operating-optics-comparison-2026-08-11.md:The stronger conclusion is that some of the archive's most interesting quarters are not best read straight off the reported margin line."
  "analysis/cross-sector/policy-distorted-operating-optics-comparison-2026-08-11.md:Beneficiary Versus Burden Carrier Map"
  "site/concrete-insights.html:AI capacity burden carrier comparison"
  "site/concrete-insights.html:Insight completion rubric"
  "site/concrete-insights.html:Recreation lifestyle and occasion demand comparison"
  "site/concrete-insights.html:Paid relationship and habit loop comparison"
  "site/concrete-insights.html:Status wallet and default spend comparison"
  "site/concrete-insights.html:Continuity and maintenance economics comparison"
  "site/concrete-insights.html:Institutional overhead and control-plane comparison"
  "site/concrete-insights.html:Coordination toll without asset ownership comparison"
  "site/concrete-insights.html:Closed-loop ecosystem versus open routing comparison"
  "site/concrete-insights.html:Access instead of ownership comparison"
  "site/concrete-insights.html:Self-maintenance and confidence spend comparison"
  "site/concrete-insights.html:Discovery and decision reduction comparison"
  "site/concrete-insights.html:Relationship thickening and second-layer monetization comparison"
  "site/concrete-insights.html:Standardization and simplification as product comparison"
  "site/concrete-insights.html:Delegated operations and outsourced complexity comparison"
  "site/concrete-insights.html:Failure avoidance and uptime economics comparison"
  "site/concrete-insights.html:Compliance and mandated spend economics comparison"
  "site/concrete-insights.html:Specialist labor and certified capacity comparison"
  "site/concrete-insights.html:Density and local coverage as moat comparison"
  "site/concrete-insights.html:Institutional adaptation and capability outsourcing comparison"
  "site/concrete-insights.html:Aging as operating reality comparison"
  "site/concrete-insights.html:Beauty discovery and data interface comparison"
  "site/concrete-insights.html:Healthcare burden versus workflow comparison"
  "site/concrete-insights.html:Healthcare testing distribution and delivery comparison"
  "site/concrete-insights.html:Trust proof measurement and security comparison"
  "site/concrete-insights.html:Commodity chain comparison"
  "site/concrete-insights.html:Media attention helper comparison"
  "site/concrete-insights.html:Media owner versus helper economics comparison"
  "site/concrete-insights.html:Interface ownership and demand orchestration comparison"
  "site/concrete-insights.html:Point-of-use control and qualified interface comparison"
  "site/concrete-insights.html:Narrow chokepoint and disproportionate consequence comparison"
  "site/concrete-insights.html:Qualification, validation, and reapproval friction comparison"
  "site/concrete-insights.html:Installed-base and pull-through economics comparison"
  "site/concrete-insights.html:Accepted record and auditable workflow control comparison"
  "site/concrete-insights.html:Frontline visibility and executable workflow comparison"
  "site/concrete-insights.html:Labor production infrastructure comparison"
  "site/concrete-insights.html:Machine-readable operating state comparison"
  "site/concrete-insights.html:Outsourced judgment and benchmark authority comparison"
  "site/concrete-insights.html:Packaging as demand sensor and product interface comparison"
  "site/concrete-insights.html:Low-friction entrepreneurship infrastructure comparison"
  "site/concrete-insights.html:Deferred commitment and conversion infrastructure comparison"
  "site/concrete-insights.html:Intent capture and agentic commerce interface comparison"
  "site/concrete-insights.html:Externally supplied inventory and participation economics comparison"
  "site/concrete-insights.html:Governance burden on participant platforms comparison"
  "site/concrete-insights.html:Replenishment without subscription comparison"
  "site/concrete-insights.html:Home as managed service endpoint comparison"
  "site/concrete-insights.html:Portfolio surgery and burden shedding comparison"
  "site/concrete-insights.html:Affordability engineering and value reinvestment comparison"
  "site/concrete-insights.html:AI readiness and usable context stack comparison"
  "site/concrete-insights.html:Balance-sheet velocity and timing economics comparison"
  "site/concrete-insights.html:Pre-collected demand and obligation-backed visibility comparison"
  "site/concrete-insights.html:Formalized price architecture and approved increase systems comparison"
  "site/concrete-insights.html:Policy-distorted operating optics comparison"
  "site/concrete-insights.html:Relationship ownership versus property burden comparison"
  "site/index.html:Insight extraction hub"
  "site/index.html:Meaty end-to-end insight goal"
  "site/index.html:Lane end-to-end execution runbook"
  "site/index.html:Insight-driven next lane queue"
  "site/concrete-insights.html:Insight extraction hub"
  "site/concrete-insights.html:Meaty end-to-end insight goal"
  "site/concrete-insights.html:Lane end-to-end execution runbook"
  "site/concrete-insights.html:Insight-driven next lane queue"
)

for path in "${required_files[@]}"; do
  if [[ ! -s "$path" ]]; then
    printf 'missing or empty required file: %s\n' "$path" >&2
    exit 1
  fi
done

mapfile -t reusable_note_files < <(rg -v '^\s*(#|$)' "$reusable_note_manifest")

if [[ "${#reusable_note_files[@]}" -eq 0 ]]; then
  printf 'reusable note manifest is empty: %s\n' "$reusable_note_manifest" >&2
  exit 1
fi

bash scripts/audit-note-layer-boundary.sh >/dev/null

for path in "${reusable_note_files[@]}"; do
  if [[ ! -s "$path" ]]; then
    printf 'missing reusable note file: %s\n' "$path" >&2
    exit 1
  fi
  if ! rg -q '^## Packet Inputs Used' "$path"; then
    printf 'reusable note missing Packet Inputs Used section: %s\n' "$path" >&2
    exit 1
  fi
  if ! rg -q '^## Skeptical Reader Test' "$path"; then
    printf 'reusable note missing Skeptical Reader Test section: %s\n' "$path" >&2
    exit 1
  fi
done

tmp_report="$(mktemp)"
tmp_json="$(mktemp)"
trap 'rm -f "$tmp_report" "$tmp_json"' EXIT
bash scripts/audit-note-layer-boundary.sh --write-report "$tmp_report" >/dev/null
if ! cmp -s "$note_boundary_report" "$tmp_report"; then
  printf 'stale note boundary report: %s\n' "$note_boundary_report" >&2
  printf 'regenerate with: bash scripts/audit-note-layer-boundary.sh --write-report %s\n' "$note_boundary_report" >&2
  exit 1
fi

bash scripts/audit-note-layer-boundary.sh --write-json "$tmp_json" >/dev/null
if ! cmp -s "$note_boundary_json" "$tmp_json"; then
  printf 'stale note boundary json summary: %s\n' "$note_boundary_json" >&2
  printf 'regenerate with: bash scripts/audit-note-layer-boundary.sh --write-json %s\n' "$note_boundary_json" >&2
  exit 1
fi

for item in "${required_patterns[@]}"; do
  path="${item%%:*}"
  pattern="${item#*:}"
  if ! rg -q --fixed-strings "$pattern" "$path"; then
    printf 'missing required pattern in %s: %s\n' "$path" "$pattern" >&2
    exit 1
  fi
done

printf 'insight-system-ok\n'
